### ISSUE TITLE
Überwachung im öffentlichen Raum

### ISSUE THREAD

**Issue by RnBCoder** [arpr/UNP-AG-12#12]
pr0tokoll hat es ja bereits im Discord geschickt, ein Projekt für Gesichtserkennung im öffentlichen Raum ist gerade in eine Testphase übergegangen.

[https://www.heise.de/newsticker/meldung/Automatische-Gesichtserkennung-Test-der-Bundespolizei-bringt-gesteigertes-Sicherheitsgefuehl-oder-3789990.html](url)

Es reicht auch wenn man Gesichtserkennung googelt, da findet man dann vermehrt Artikel zum gleichen Test.

Jetzt ist die Frage, wird das ein weiterer Punkt im Programm? Generell Videokameras im öffentlichen Raum?
Überschneidet sich eventuell mit Vorratsdatenspeicherung?

Ich persönlich habe nichts gegen Videoüberwachung an solchen Plätzen, wenn nach einer Frist das Material gelöscht wird und nur bei Tatverdacht verwendet wird, aber Gesichtserkennung? Falls das kommt laufe ich nur noch mit Halstuch über die Nase gezogen rum.

**Comment by Vetm** [comment]
Die Gesichtserkennung finde ich aus Datenschutz-Sicht extrem bedenklich. Wenn so ein System bundesweit umgesetzt wird können von jedem Bürger problemlos Bewegungsprofile angelegt werden. Auch eine Ortung in Echtzeit wäre möglich.

Dass durch dieses System eine erhöhte Sicherheit entsteht bezweifle ich sehr stark. Für Straftäter o.Ä. sollte es einfach sein dieses System zu umgehen. Bspw. wie du bereits angedeutet hast durch Kopfbedeckungen oder Halstücher. Es gibt sogar schon spezielle Lösungen gegen Gesichtserkennung:
https://www.hackread.com/reflectacles-anti-facial-recognition-glasses/
https://cvdazzle.com/
Ich bin mir sicher, dass eine einfache optische Gesichtserkennung in fast jedem Fall umgangen werden kann (wenn man es möchte).

Dieses System würde also höchstens zu einer verstärkten Überwachung der breiten Masse führen und könnte von Straftätern/Terroristen einfach umgangen werden.

**Comment by arpr** [comment]
Ich bin dafür dieses Thema für die nächste Sitzung mit auf die Tagesordnung zu nehmen.
Bitte abstimmen.

**Comment by ExNought** [comment]
Zu dem Punkt kann ich nur hinzufügen, was ich bei der VDS und beim Bundestrojaner gesagt habe und wie es beispielsweise bei der Maut auch gehandhabt wurde.

Schön und gut, kann helfen, ist nicht erwiesen und in ein paar Jahren/Monaten werden die Befugnisse erweitert, dann dürfen alle Behörden drauf zugreifen und irgendwann auch Private und spätestens dann ist die Werbebranche am rotieren. Bin ich strikt dagegen, schlicht weil sich bisher gezeigt hat, dass der Staat mit einer solchen Verwantwortung nicht umgehen kann!
