### ISSUE TITLE
Titel für "Youtube"-Abschnitt

### ISSUE THREAD

**Issue by arpr** [arpr/UNP-AG-12#3]
"Youtuber in Deutschland" - zu weitläufig, zu ungenau?
"Rundfunklizenz für Streamer/Content-creator"
"Rundfunklizenz für Inhalte-Ersteller?" - zu spezifisch, zu "englisch"?

"Rundfunklizenz für Online-Video-Angebote" ?

**Comment by 5yn74x** [comment]
Rundfunklizenz für Online-Übertragungs-Angebote

**Comment by HannesMi** [comment]
Eventuell besser:
Rundfunklizenz für Online-Medien-Angebote

**Comment by arpr** [comment]
Wir werden weitere Vorschläge hier und beim Brainstorming sammeln und dann abstimmen.
