### ISSUE TITLE
Aufnahme ins Programm: "Jugendschutz"

### ISSUE THREAD

**Issue by arpr** [arpr/UNP-AG-12#4]
bitte abstimmen.

**Comment by ExNought** [comment]
Gehört das komplett zu uns? Meines Erachtens nach ist das eher nur das Durchsetzen von Jugendschutz im Netz ;)

**Comment by arpr** [comment]
> nur das Durchsetzen von Jugendschutz im Netz

Soll sich die UNP dafür einsetzen? Wenn ja, wie kann soetwas aussehen? 
Oder sollen sich die Erziehungsberechtigten alleine darum kümmern?
