### ISSUE TITLE
Aufnahme ins Programm: Große Internetplattformen wie Facebook, Youtube, Twitter,.

### ISSUE THREAD

**Issue by arpr** [arpr/UNP-AG-12#5]
Ein User namens "NUMM3R0815" hat einen Vorschlag gemacht zu Datenschutz:

## Große Internetplattformen wie Facebook, Youtube, Twitter,.
.. haben durch ihre Größe und Reichweite einen neuen, bisher nie dagewesenen Stellenwert in Sachen Meinungsbildung und Information erreicht. Wegen ihrer Komplexität und dem besonderen Einfluss auf Menschen, der vorher noch nicht möglich war, muss eine Anpassung ihres Rechts auf Kontrolle über angezeigte Inhalte vorgenommen werden. Der Einfluss dieser Unternehmen auf die Gesellschaft (ausgeübt unterschwellig mit komplexesten Sortier- und Filteralgorithmen) ist zu hoch, um ihnen die alleinige Kontrolle über Inhalte zu überlassen. Sie besitzen die Macht, durch direkte, individuelle Einflussnahme auf einen großen Teil der Bevölkerung, deren Denken nach ihren eigenen Interessen zu verändern, ohne dass dies nachprüfbar oder ersichtlich wäre. 
Angesichts dessen, dass heute schon Wahlen mit Daten aus und Beiträgen in sozialen Netzwerken gewonnen werden, sind die Möglichkeiten der Einflussnahme durch besagte Firmen unabschätzbar, aber zweifellos demokratiegefährdend. 
Aus diesem Grund sollten Internetplattformen ab einer bestimmten Nutzeranzahl sich verpflichten, keine gezielten Manipulationen an ihren Nutzern vorzunehmen. Dies sollte überprüfbar sein und bei Missachtung harte Konsequenzen bedeuten.

**Comment by HannesMi** [comment]
Ist meiner Meinung nach Existent: siehe Zensur im Internet / Netzneutralität

**Comment by 5yn74x** [comment]
> Ist meiner Meinung nach Existent: siehe Zensur im Internet / Netzneutralität
Sollte aber mMn. als Unterthema aufgeführt werden.
