### ISSUE TITLE
Neutralität im europäischen Vergleich (Bezogen auf Datentarife und Glasfaserausbau)

### ISSUE THREAD

**Issue by 5yn74x** [arpr/UNP-AG-12#7]
Gerade in ländlichen Gebieten ist LTE nicht immer flächendeckend verfügbar und wenn mitunter nur ausschließlich,
was dazu führt, dass die Anwohner auf LTE angewiesen sind, um eine "menschenwürdige" Übertragungsrate nutzen zu können.

Die Nachteile dessen sind, dass die Provider dem Verbraucher hohe Kosten für das Übertragungsvolumen auferlegen. 

**Meine Forderungen:**

- Verfügbarkeit eines schnellen Internetanschlusses als Grundrecht
- LTE nur als Notlösung -> Glasfaserausbau forcieren -> LTE nur für mobile Geräte
- Mobile-Datenpackete für einen gerechten Preis  
- Glasfaserausbau bei Straßensanierung verpflichten

```
Mehr fällt mir dazu erst mal nicht ein, ich hoffe ihr habt noch Ergänzungen. 
```

**Comment by HannesMi** [comment]
Hinzuzufügen ist eventuell noch: Datentarife auf den europäischen Durchschnitt senken.
Da wir in Deutschland eine unverhältnismäßig hohe Kostenstruktur in diesem Bereich haben.
(Vgl.: https://ebook-fieber.de/smartphone/datentarife-vergleich-deutschland-gb/65148)

**Comment by 5yn74x** [comment]
> Datentarife auf den europäischen Durchschnitt senken.

Das meine ich mit "Mobile-Datenpackete für einen gerechten Preis".

> (Vgl.: https://ebook-fieber.de/smartphone/datentarife-vergleich-deutschland-gb/65148)

Auf dieser Statistik wolle ich mich auch berufen ;)

Da müssen wir halt noch mal gucken, wie man das realisiern kann.
Aber als Programmpunkt definitiv nicht verkehrt.

**Comment by arpr** [comment]
Eine Sorge die ich bei dem Thema habe, Stichwort: Preisdiktatur des Staates für Mobilfunkanbieter.
Wäre das vielleicht ein Thema für die Europa AG? Schließlich konnte das EU Parlament den privaten Netzanbietern auch kostenfreies Roaming innerhalb der EU auferlegen.

**Comment by 5yn74x** [comment]
> Preisdiktatur des Staates für Mobilfunkanbieter.

Stimmt, aber ist im Sinne des Verbraucherschutzes.
Außerdem gibt es immer Mittel und Wege das durchzusetzen, subventionierung usw.
