### ISSUE TITLE
Aufnahme ins programm "Sicherheitschecks*

### ISSUE THREAD

**Issue by mocola** [arpr/UNP-AG-12#9]
Lustboy hatte am 31.7.2017 vorgeschlagen das man sowas wie nen TÜV hat für Firmen die im Internet aktiv sind einführt.
Sprich das man einmal in jedem Quartal die firmen auf herz und niere überprüft und das wen sie
diesen test nicht bestehen sie nachrüsten müssen.

Damit kannman verhindern das wichtige daten entwendet werden und schaden angerichtet wird.

(kurz überflogen, wird noch überarbeitet)

**Comment by arpr** [comment]
Worauf bezieht sich diese Prüfung?
Datensicherheit?
